#!/bin/bash
# Define vault path
VAULT_DIR="$HOME/secure_vault"
REPORT_FILE="$VAULT_DIR/vault_report.txt"

# Check if vault exists
if [[ ! -d "$VAULT_DIR" ]]; then
    echo "ERROR: Secure vault does not exist at $VAULT_DIR"
    echo "Please run vault_setup.sh first to create the vault."
    exit 1
fi

# Initialize report
echo "+--------------------------------------------------------------+" > "$REPORT_FILE"
echo "|              SECURE VAULT MONITORING REPORT                  |" >> "$REPORT_FILE"
echo "+--------------------------------------------------------------+" >> "$REPORT_FILE"
echo "|  Generated: $(date '+%Y-%m-%d %H:%M:%S')                     |" >> "$REPORT_FILE"
echo "|  Vault Location: $VAULT_DIR                                  |" >> "$REPORT_FILE"
echo "+--------------------------------------------------------------+" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

echo "VAULT MONITORING SYSTEM"
echo "======================="
echo ""

security_risk=false

# Function to check if permissions are more open than 644
check_permission_risk() {
    local file=$1
    local perm=$(stat -c "%a" "$file")
    
    
    local user_perm=${perm:0:1}
    local group_perm=${perm:1:1}
    local other_perm=${perm:2:1}
    
    if [[ $group_perm -gt 4 ]] || [[ $other_perm -gt 4 ]]; then
        return 0 
    fi
    return 1  
}

# Monitor each file
for file in "$VAULT_DIR"/*.txt; do
    if [[ -f "$file" ]]; then
        filename=$(basename "$file")
        filesize=$(stat -c "%s" "$file")
        modified=$(stat -c "%y" "$file" | cut -d'.' -f1)
        permissions=$(stat -c "%a" "$file")
        permissions_human=$(ls -l "$file" | awk '{print $1}')
        
        echo "--------------------------------------------" >> "$REPORT_FILE"
        echo "FILE: $filename" >> "$REPORT_FILE"
        echo "--------------------------------------------" >> "$REPORT_FILE"
        echo "   Size:         $filesize bytes" >> "$REPORT_FILE"
        echo "   Modified:     $modified" >> "$REPORT_FILE"
        echo "   Permissions:  $permissions ($permissions_human)" >> "$REPORT_FILE"
        
        # Check for security risk
        if check_permission_risk "$file"; then
            echo "   WARNING: SECURITY RISK DETECTED" >> "$REPORT_FILE"
            security_risk=true
        fi
        echo "" >> "$REPORT_FILE"
        
        echo "FILE: $filename"
        echo "   Size: $filesize bytes"
        echo "   Modified: $modified"
        echo "   Permissions: $permissions ($permissions_human)"
        
        if check_permission_risk "$file"; then
            echo "   WARNING: SECURITY RISK DETECTED"
        fi
        echo ""
    fi
done

# Add summary to report
echo "--------------------------------------------" >> "$REPORT_FILE"
echo "SUMMARY" >> "$REPORT_FILE"
echo "--------------------------------------------" >> "$REPORT_FILE"
if [[ "$security_risk" == true ]]; then
    echo "WARNING: OVERALL STATUS: SECURITY RISKS DETECTED" >> "$REPORT_FILE"
    echo "   Review file permissions and restrict access as needed." >> "$REPORT_FILE"
else
    echo "OVERALL STATUS: ALL FILES SECURE" >> "$REPORT_FILE"
    echo "   No security risks detected." >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"
echo "Report generated by vault_monitor.sh" >> "$REPORT_FILE"
echo "--------------------------------------------" >> "$REPORT_FILE"


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cp "$REPORT_FILE" "$SCRIPT_DIR/vault_report.txt"

echo "--------------------------------------------"
echo "REPORT CREATED: $REPORT_FILE"
echo "REPORT COPIED TO: $SCRIPT_DIR/vault_report.txt"
echo "--------------------------------------------"

if [[ "$security_risk" == true ]]; then
    echo ""
    echo "WARNING: SECURITY RISK DETECTED - Review permissions!"
fi

